// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFAJveTg6rirgJjReDmissg2EIzixmvnc',
    appId: '1:208782505973:web:4a5de1e6d5b01c652e12bc',
    messagingSenderId: '208782505973',
    projectId: 'sdcs-270d6',
    authDomain: 'sdcs-270d6.firebaseapp.com',
    storageBucket: 'sdcs-270d6.appspot.com',
    measurementId: 'G-FPTH55Z7FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgynCBeVv6Hs9_gkAb3Q_LFzC8H2M3B5g',
    appId: '1:208782505973:android:f3d862309bb18d1d2e12bc',
    messagingSenderId: '208782505973',
    projectId: 'sdcs-270d6',
    storageBucket: 'sdcs-270d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBISrLjDa84OM6t23m0ne-CrgnMz4DgJaY',
    appId: '1:208782505973:ios:9065b0b33923d51d2e12bc',
    messagingSenderId: '208782505973',
    projectId: 'sdcs-270d6',
    storageBucket: 'sdcs-270d6.appspot.com',
    androidClientId: '208782505973-lsuqi8kjj84tto6m76f9df71pc25cg5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.sdcsData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBISrLjDa84OM6t23m0ne-CrgnMz4DgJaY',
    appId: '1:208782505973:ios:9065b0b33923d51d2e12bc',
    messagingSenderId: '208782505973',
    projectId: 'sdcs-270d6',
    storageBucket: 'sdcs-270d6.appspot.com',
    androidClientId: '208782505973-lsuqi8kjj84tto6m76f9df71pc25cg5p.apps.googleusercontent.com',
    iosBundleId: 'com.example.sdcsData',
  );
}
